# === Website information ===
title: "</MDesign>"
description: "Personal website of Martin Dimitrov." 
url: "https://martindimitrov.dev"
email: "martin.dimi.dev@yandex.com"

# === Social ===
social:
  github: "https://github.com/martindimi"
  linkedin: "https://www.linkedin.com/in/martin-dimitrov-20ba621a6/"
  fiverr: "https://www.fiverr.com/martindimi27"

# === Jekyll Configuration ==
markdown: kramdown

exclude:
  - LICENCE
  - README.md

include:
  - "_pages"
  - ".htaccess"

# === Build settings ===
destination: mdesign-build/

# === Plugins ===
plugins:
  - jekyll-sitemap

# === SASS Settings ===
sass:
  sass_dir: _sass
  style: compressed

# === Defaults ===
defaults:
  - 
    scope:
      type: "posts"
    values:
      layout: project
      permalink: "/my-work/:title"