# === Website information ===
title: "</MDesign>"
description: "Personal website of Martin Dimitrov."
url: "https://m-design.dev"
email: "martin.dimi.dev@yandex.com"

# === Social ===
social:
  github: "https://github.com/martindimi"
  dribbble: "https://dribbble.com/martindimi"
  linkedin: "https://www.linkedin.com/in/martin-dimitrov-20ba621a6/"
  fiverr: "https://www.fiverr.com/martindimi27"

# === Jekyll Configuration ==
markdown: kramdown

exclude:
  - LICENCE
  - README.md

include:
  - "_pages"
  - ".htaccess"

# === Build settings ===
destination: mdesign-build/

# === Plugins ===
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# === SASS Settings ===
sass:
  sass_dir: _sass
  style: compressed

# === Defaults ===
defaults:
  - 
    scope:
      type: "posts"
    values:
      layout: project
      permalink: "/my-work/:title"

# === SEO Settiings ===
webmaster_verifications:
  google: B1282SvdgoKQ2TG2qIg1I54bwxj_5wjdeYlDOdTHr-U
  bing: 38E2D6C346519BDADAB7843E177A9364
  yandex: 83ee8782b4fee935

